var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
var age = 25;
console.log("Is age > 18? I predict True.");
console.log(age > 18);
console.log("Is age < 20? I predict False.");
console.log(age < 20);
var temperature = 30;
console.log("Is temperature >= 25? I predict True.");
console.log(temperature >= 25);
console.log("Is temperature <= 20? I predict False.");
console.log(temperature <= 20);
var isRainy = false;
console.log("Is it rainy? I predict False.");
console.log(isRainy);
console.log("Is it sunny? I predict True.");
console.log(!isRainy);
var fruit = 'apple';
console.log("Is fruit == 'apple'? I predict True.");
console.log(fruit == 'apple');
console.log("Is fruit == 'banana'? I predict False.");
console.log(fruit == 'banana');
var isStudent = true;
console.log("Is the person a student? I predict True.");
console.log(isStudent);
console.log("Is the person an employee? I predict False.");
console.log(!isStudent);
